# app/config.py

SEVERITY_WEIGHTS = {
    "low": 2,
    "medium": 5,
    "high": 10
}

WARNING_THRESHOLD = 8
CANCELLATION_THRESHOLD = 15

BURST_TIME_WINDOW_SECONDS = 120
BURST_COUNT_THRESHOLD = 3

REPEAT_HIGH_VIOLATION_THRESHOLD = 2